# Numpy

## 1.Creating arrays

In [3]:
import numpy as np

In [163]:
# create a numpy array of 20 random integers between 10 and 50
random_array = np.random.randint(10,50, size=20)
print("Random Array:",random_array)

Random Array: [20 41 22 17 35 41 17 47 45 24 46 20 34 38 26 12 17 17 38 26]


## 2.Array reshaping

In [165]:
# Create a 2D NumPy array of shape (6, 5) fi lled with random fl oats between 0 and 1. Reshape this array to have shape (5, 6) and print both the original and reshaped arrays.

original_array = np.random.rand(6,5)
reshaped_array = original_array.reshape(5,6)
print("Original Array (6,5):",original_array)
print("Reshaped Array (5,6):",reshaped_array)

Original Array (6,5): [[0.68021644 0.17914769 0.72565551 0.46044827 0.25412749]
 [0.90841897 0.37058862 0.54549573 0.73646709 0.04818533]
 [0.09389809 0.23794764 0.10464114 0.03084223 0.71289388]
 [0.25808815 0.23748303 0.44988044 0.7541641  0.4836457 ]
 [0.9970047  0.20606885 0.25234917 0.50999703 0.49473712]
 [0.07421766 0.36726312 0.26792508 0.48162001 0.56252517]]
Reshaped Array (5,6): [[0.68021644 0.17914769 0.72565551 0.46044827 0.25412749 0.90841897]
 [0.37058862 0.54549573 0.73646709 0.04818533 0.09389809 0.23794764]
 [0.10464114 0.03084223 0.71289388 0.25808815 0.23748303 0.44988044]
 [0.7541641  0.4836457  0.9970047  0.20606885 0.25234917 0.50999703]
 [0.49473712 0.07421766 0.36726312 0.26792508 0.48162001 0.56252517]]


## 3.Array Indexing and Slicing

In [21]:
# Create a 2D array of shape (5, 5) fi lled with numbers from 1 to 25. Extract a subarray that includes rows 2 to 4 and columns 1 to 3.

array = np.arange(1,26).reshape(5,5)
subarray = array[1:4,0:3]
print("Original Array:")
print(array)
print("Sub Array(rows 2 to 4,columns 1 to 3):",subarray)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Sub Array(rows 2 to 4,columns 1 to 3): [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


## 4.Array Operations

In [24]:
# Generate two 1D arrays A and B, each containing 10 random integers between 1 and 100. Add the arrays together, then multiply the result by 2. Show the results of each operation.

A = np.random.randint(1,101,size=10)
B = np.random.randint(1,101,size=10)
sum_array = A + B
result_array = sum_array*2
print("Array A:",A)
print("Array B:",B)
print("Sum of A and B:",sum_array)
print("Result of after multiplying by 2:",result_array)

Array A: [55 50 24 30 44 72 41 92 22 32]
Array B: [72 77 11 67 65 68 87 94 61 18]
Sum of A and B: [127 127  35  97 109 140 128 186  83  50]
Result of after multiplying by 2: [254 254  70 194 218 280 256 372 166 100]


## 5.Broadcasting

In [28]:
# Create a 2D array A of shape (3, 4) filled with random integers between 1 and 10. Create a 1D array B of shape (4,) with values [1, 2, 3, 4]. Add the 1D array to the 2D array and explain how broadcasting works in this case

A = np.random.randint(1,11,size=(3,4))
B = np.array([1,2,3,4])
result = A + B
print("Array A(3,4):",A)
print("Array b(4,):",B)
print("Result of A+B:",result)


Array A(3,4): [[6 8 1 7]
 [4 3 3 3]
 [1 4 7 9]]
Array b(4,): [1 2 3 4]
Result of A+B: [[ 7 10  4 11]
 [ 5  5  6  7]
 [ 2  6 10 13]]


## 6.Finding Maximum/Minimum Values

In [33]:
# Create a 3x3 matrix of random integers between 1 and 100. Find the row with the maximum sum, and then the maximum value in that row.

matrix = np.random.randint(1,101,size=(3,3))
row_sums = np.sum(matrix, axis=1)
max_row_index = np.argmax(row_sums)
max_value_in_row = np.max(matrix[max_row_index])
print("Matrix:",matrix)
print("Row sums:",row_sums)
print("Row with maximum sum(index):",max_row_index)
print("Maximum value in the row:",max_value_in_row)

Matrix: [[44  2 65]
 [87 67 28]
 [66 36 40]]
Row sums: [111 182 142]
Row with maximum sum(index): 1
Maximum value in the row: 87


## 7.Linear Algebra

In [36]:
# Create two 2D arrays A and B, both of shape (2, 2), fi lled with random integers. Compute the matrix multiplication of A and B using np.dot().

A = np.random.randint(1,101,size=(2,2))
B = np.random.randint(1,101,size=(2,2))
result = np.dot(A,B)
print("Array A:",A)
print("Array B:",B)
print("A*B:",result)

Array A: [[54 77]
 [22 85]]
Array B: [[94 91]
 [85 19]]
A*B: [[11621  6377]
 [ 9293  3617]]


## 8. Boolean Indexing

In [39]:
# Create an array of shape (6, 6) with random integers between 1 and 50. Using boolean indexing, extract all values greater than 25.

array = np.random.randint(1,51,size=(6,6))
values_greater_than_25 = array[array>25]
print("Array:",array)
print("Values grater than 25:",values_greater_than_25)

Array: [[31  3 23  7 23 22]
 [20 30  2 10 44 15]
 [14 20  4 37 43 33]
 [14 14 38 26 21  7]
 [32 14 20 19 42 31]
 [38  4 18 12 12 30]]
Values grater than 25: [31 30 44 37 43 33 38 26 32 42 31 38 30]


## 9.Statistics

In [42]:
# Create a 5x5 array of random floats between 0 and 1. Calculate the median and variance along the columns and rows separately.

array = np.random.rand(5,5)
median_rows = np.median(array,axis=1)
median_columns = np.median(array,axis=0)
variance_rows = np.var(array,axis=1)
variance_columns = np.var(array,axis=0)
print("Array:",array)
print("Median along rows:",median_rows)
print("Median along columns:",median_columns)
print("Variance along rows:",variance_rows)
print("Variance along columns:",variance_columns)


Array: [[0.6491761  0.5918937  0.5358393  0.02681592 0.67800523]
 [0.25707558 0.66153741 0.90647202 0.13282424 0.13713131]
 [0.26073912 0.67877481 0.38992782 0.00611117 0.72505388]
 [0.88815663 0.26138722 0.37355515 0.24948449 0.72491628]
 [0.9784503  0.24812678 0.94510389 0.60877823 0.44479558]]
Median along rows: [0.5918937  0.25707558 0.38992782 0.37355515 0.60877823]
Median along columns: [0.6491761  0.5918937  0.5358393  0.13282424 0.67800523]
Variance along rows: [0.05750094 0.09680388 0.07145685 0.06738681 0.08003072]
Variance along columns: [0.0922293  0.03723922 0.06159839 0.04830624 0.05176637]


## 10. Element-wise Operations

In [47]:
# Generate a 3x3 matrix of random integers between 1 and 10. Perform the following element-wise operations: subtract 2 from each element, square each element, and compute the reciprocal of each element.

matrix = np.random.randint(1,11,size=(3,3))
subtracted_matrix = matrix - 2
squared_matrix = np.power(matrix,2)
reciprocal_matrix = 1/matrix

print("Matrix:",matrix)
print("Matrix after subtracting2:",subtracted_matrix)
print("Matrix after squaring each element:",squared_matrix)
print("Matrix after computing reciprocals:",reciprocal_matrix)

Matrix: [[8 3 5]
 [4 1 5]
 [7 3 7]]
Matrix after subtracting2: [[ 6  1  3]
 [ 2 -1  3]
 [ 5  1  5]]
Matrix after squaring each element: [[64  9 25]
 [16  1 25]
 [49  9 49]]
Matrix after computing reciprocals: [[0.125      0.33333333 0.2       ]
 [0.25       1.         0.2       ]
 [0.14285714 0.33333333 0.14285714]]


# Pandas

## 1.Basic Exploration

In [54]:
# Basic Exploration Load the dataset into a Pandas DataFrame. Display: 
# The fi rst 10 rows
# The total number of rows and columns 
# Summary statistics for numerical columns

In [56]:
import pandas as pd

In [60]:
df = pd.read_csv("auto-mpg.csv")

In [66]:
print("First 10 rows:")
(df.head(10))

First 10 rows:


mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [68]:
print("Total number of rows and columns:")
df.shape

Total number of rows and columns:


(398, 9)

In [70]:
print("Summary statistics for numerical columns:")
df.describe()

Summary statistics for numerical columns:


mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

## 2. Filtering and Indexing

In [83]:
# Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg.

filtered_df = df[(df["model year"] ==1975) & (df["weight"]<3000)]
result = filtered_df[["car name","weight","mpg"]]
print("Cars manufactured in 1975 with weight less than 3000:")
print(result)

Cars manufactured in 1975 with weight less than 3000:
Empty DataFrame
Columns: [car name, weight, mpg]
Index: []


## 3. Handling Missing Data

In [86]:
# Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.



In [109]:


# Convert 'horsepower' and 'weight' columns to numeric, coercing errors to NaN
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')

# Handle missing values (optional: replace them with the median)
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)
df['weight'].fillna(df['weight'].median(), inplace=True)

# Add the power_to_weight_ratio column
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']

# Display the updated DataFrame (first few rows)
print(df[['horsepower', 'weight', 'power_to_weight_ratio']].head())


   horsepower  weight  power_to_weight_ratio
0       130.0    3504               0.037100
1       165.0    3693               0.044679
2       150.0    3436               0.043655
3       150.0    3433               0.043694
4       140.0    3449               0.040591


C:\Users\DELL\AppData\Local\Temp\ipykernel_8352\2604821126.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].median(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_8352\2604821126.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a co

In [111]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

# Replace missing values in the 'horsepower' column with the median of the column
if 'horsepower' in df.columns:
    median_horsepower = df['horsepower'].median(skipna=True)  # Calculate the median
    df['horsepower'].fillna(median_horsepower, inplace=True)  # Replace missing values
    print("\nUpdated 'horsepower' Column:")
    print(df['horsepower'])

Missing Values in Each Column:
mpg                      0
cylinders                0
displacement             0
horsepower               0
weight                   0
acceleration             0
model year               0
origin                   0
car name                 0
power_to_weight_ratio    0
dtype: int64

Updated 'horsepower' Column:
0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64


C:\Users\DELL\AppData\Local\Temp\ipykernel_8352\1722241453.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(median_horsepower, inplace=True)  # Replace missing values


## 4. Data Transformation

In [113]:
# Add a new column power_to_weight_ratio, calculated as horsepower / weight.

df["power_to_weight_ratio"] = df["horsepower"] / df["weight"]
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

## 5.Group by

In [121]:
# Group the cars by origin and calculate the mean mpg for each group.

mean_mpg_by_origin = df.groupby("origin")["mpg"].mean()
print("Mean mpg by origin:",mean_mpg_by_origin)
                                

Mean mpg by origin: origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64


## 6.Sorting

In [126]:
# Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

top_10_mpg = df.sort_values(by="mpg",ascending=False).head(10)
print("Top 10 cars with highest mpg:",top_10_mpg)
df.head()

Top 10 cars with highest mpg:       mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl 

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

In [130]:

def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
                                   
print("DataFrame with Performance Score:")
print(df[['mpg', 'acceleration', 'weight', 'performance_score']].head())


DataFrame with Performance Score:
    mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754


## 7.Apply this function to each row and store the result in the new column.

In [133]:

def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
print(df[['mpg', 'acceleration', 'weight', 'performance_score']].head())


    mpg  acceleration  weight  performance_score
0  18.0          12.0    3504           0.061644
1  15.0          11.5    3693           0.046710
2  18.0          11.0    3436           0.057625
3  16.0          12.0    3433           0.055928
4  17.0          10.5    3449           0.051754


## 8. Visualization Preparation

In [144]:
# Generate a summary DataFrame with:
 # Average mpg, weight, and horsepower for each model_year.

summary = df.groupby("model year")[["mpg","weight","horsepower"]].mean().reset_index()
print("Summary dataframe with Averages:")
print(summary)



Summary dataframe with Averages:
    model year        mpg       weight  horsepower
0           70  17.689655  3372.793103  147.827586
1           71  21.250000  2995.428571  106.553571
2           72  18.714286  3237.714286  120.178571
3           73  17.100000  3419.025000  130.475000
4           74  22.703704  2877.925926   94.203704
5           75  20.266667  3176.800000  101.066667
6           76  21.573529  3078.735294  101.117647
7           77  23.375000  2997.357143  105.071429
8           78  24.061111  2861.805556   99.694444
9           79  25.093103  3055.344828  101.206897
10          80  33.696552  2436.655172   78.586207
11          81  30.334483  2522.931034   81.465517
12          82  31.709677  2453.548387   81.854839


## 9.Exporting Data

In [167]:
# Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV fi le named high_mpg_cars.csv.

subset = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]
subset.to_csv('high_mpg_cars.csv', index=False)
print("Subset saved to high_mpg_cars.csv")

Subset saved to high_mpg_cars.csv


## 10.Finding Anomalies

In [150]:
#Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifically:
# Calculate the IQR for mpg.
# Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.
# Create a DataFrame of cars classified as outliers, displaying car_name, mpg, and model_year.



In [156]:
Q1 =df['mpg'].quantile(0.25)
Q3 =df['mpg'].quantile(0.75)
IQR = Q3 -Q1

lower_bound = Q1 -1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['mpg']<lower_bound) | (df['mpg']>upper_bound)]
outliers_df = outliers[['car name','mpg','model year']]

print("Cars classified as outliers:")
(outliers_df)

Cars classified as outliers:


car name   mpg  model year
322  mazda glc  46.6          80